version: '3.1'
services:
  app:
    container_name: express-app
    restart: unless-stopped
    image: node
    command: npm run dev:app
    ports:
      - 8080:8080
    volumes:
      - .:/app:rw
    working_dir: /app
