#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Styling, testing, and building your project before committing'

# Prettier
npm run prettier:check ||
(
  echo 'Prettier Check Failed. Execute npm run prettier before recommitting.';
  false;
)

# Check ESLint Standards
npm run lint ||
(
  echo 'ESLint Check Failed. Make required changes listed above before recommitting.'
  false; 
)

# Check tsconfig standards
npm run typecheck ||
(
  echo 'Tpye Check Failed Type check. Make the changes required above before recommitting.'
  false;
)

# Check Jest tests
# npm run test -- --watchAll=false ||
# (
#     echo 'Jest Check Failed. Make required changes listed above before recommitting.'
#     false;
# )

# If everything passes... Now we can commit
echo 'Code has passed all tests. Attempting to build project.'

npm run build ||
(
  echo 'Build failed: View the errors above to see why.'
  false;
)

# If everything passes... Now we can commit
echo 'pre-commit checks passed, committing code.'